version: '3'
services:
  database:
    image: postgres:13.1-alpine
    container_name: database
    volumes:
      - car_selling_service_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 2212
      POSTGRES_DB: car_selling_service
      PGDATA: /var/lib/postgresql/data
    networks:
      - car_selling_service_network
    restart: always
  back:
    image: riezenmark/car_selling_service_back:v1
    container_name: backend
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/car_selling_service
    networks:
      - car_selling_service_network
    restart: always
  front:
    image: riezenmark/car_selling_service_front:v1
    container_name: frontend
    ports:
      - 9000:8080
    networks:
      - car_selling_service_network
    restart: always
volumes:
  car_selling_service_db:
networks:
  car_selling_service_network: